// Generated API types - DO NOT EDIT
// Auto-generated by Orval from backend OpenAPI schema
// Run: pnpm gen:contract

// Re-export all types from the types package
export type {
  // Entities
  Restaurant,
  MenuCategory,
  MenuItem,
  Customer,
  DiningTable,
  Staff,
  InventoryItem,

  // Orders
  Order,
  OrderItem,
  OrderStatus,
  OrderType,
  PaymentStatus,
  CreateOrderPayload,
  UpdateOrderPayload,
  AddOrderItemPayload,
} from '@restaurant/types';
